spring.application.name=project management system

#Database config
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/project_management_system
spring.datasource.username=javaproject
spring.datasource.password=javaproject
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#logging config
spring.jpa.show-sql: true

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jitprakashstudy2025@gmail.com
spring.mail.password=hegn mkpr levc wfkr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true